"""
Django settings for erp project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-3ii5d7t-1w*9_t3gw!%_*lcv$bk0291dr-*y11nk@7)+1^efzm'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# CSRF Trusted Origins - Add your domain/port combinations here
CSRF_TRUSTED_ORIGINS = [
    'http://103.14.120.216:30000',
    'http://103.14.120.216:80',
    'http://103.14.120.216',
    'https://103.14.120.216:30000',
    'https://103.14.120.216:80',
    'https://103.14.120.216',
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_crontab',
    'payroll',
    'security',
    'procurement'
]

CRONJOBS = [
    # ('*/1 * * * *', 'payroll.cron.send_notification'),
    ('0 0 * * *', 'payroll.cron.send_notification')
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'erp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, "templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'payroll.context_processors.gender_data',
                'payroll.context_processors.get_paycycle',
                'payroll.context_processors.get_status',
                'payroll.context_processors.mar_status',
                'payroll.context_processors.grade_code',
                'payroll.context_processors.desig',
                'payroll.context_processors.dept',
                'payroll.context_processors.employee',
                'payroll.context_processors.process_flag',
                'payroll.context_processors.at_uom',
                'payroll.context_processors.project',
                'payroll.context_processors.pro_type',
                'payroll.context_processors.pro_city',
                'payroll.context_processors.nationality',
                'payroll.context_processors.hol_type',
                'payroll.context_processors.get_pay_process_flag',
                'payroll.context_processors.get_country',
                'payroll.context_processors.get_place',
                'payroll.context_processors.get_bank',
                'payroll.context_processors.get_branch',
                'payroll.context_processors.get_documents',
                'payroll.context_processors.get_earnings',
                'payroll.context_processors.get_deductions',
                'payroll.context_processors.get_relatives',
                'payroll.context_processors.get_other_documents',
                'payroll.context_processors.get_emirates',
                'payroll.context_processors.get_work_location',
                'payroll.context_processors.get_service_type',
                'payroll.context_processors.get_pro_sub_location',
                'payroll.context_processors.get_nationality',
                'payroll.context_processors.get_company_documents',
                'payroll.context_processors.get_floor',
                'payroll.context_processors.get_room_type',
                'payroll.context_processors.get_currency',
                'payroll.context_processors.get_camp',
                'payroll.context_processors.get_customer',
                'payroll.context_processors.get_uom',
                'payroll.context_processors.get_pr_items',
                'payroll.context_processors.get_item_categories',
                'payroll.context_processors.get_item_sub_categories',
                'payroll.context_processors.get_warehouse_types',
                'payroll.context_processors.get_party_type',
                'payroll.context_processors.get_leave_types',
                'payroll.context_processors.get_staff_category',
                'payroll.context_processors.get_company',
                'payroll.context_processors.get_pass_reason',
                'payroll.context_processors.get_agent', 
                'payroll.context_processors.get_grade_code',
                'payroll.context_processors.get_project_status',
                'payroll.context_processors.pro_type',
                'payroll.context_processors.get_l_and_p',
                'payroll.context_processors.get_doc_expiry'

            ],
        },
    },
]

WSGI_APPLICATION = 'erp.wsgi.application'



# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'ERP',
#         'USER': 'ERP',
#         'PASSWORD': 'Windows*1',
#         'HOST': '103.91.187.48',
#         'PORT': '3306'
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'erp_uat',
        'USER': 'postgres',
        'PASSWORD': 'Windows*1',
        'HOST': '103.14.120.216',
        # 'HOST': '92.96.253.84',
        'PORT': '5432',
        'OPTIONS': {
            'sslmode': 'disable'
        }
    },
    # 'oracle': {
    #     'ENGINE': 'django.db.backends.oracle',
    #     'NAME': 'sanaerp.oracleapexservices.com:1521/XEPDB1',
    #     'USER': 'sanaerp68',
    #     'PASSWORD': 'snVpaEtbL6',
    #     'HOST': '',
    #     'PORT': '',
    # }
}

# Database Router Configuration
# DATABASE_ROUTERS = ['erp.database_router.DatabaseRouter']

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'ERP1',
#         'USER': 'postgres',
#         'PASSWORD': 'Postgres',
#         'HOST': 'localhost', 
#         'PORT': '5432',
#     }
# }




# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

STATIC_ROOT = BASE_DIR/ 'staticfiles'

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

#MEDIA

MEDIA_URL = 'media/'

MEDIA_ROOT = BASE_DIR / "media"

# Add this setting to allow your site to be displayed in an iframe
X_FRAME_OPTIONS = 'ALLOWALL'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Email Configuration
# For testing - emails will be printed to console
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

# For production - use SMTP
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'ferosek13@gmail.com'
EMAIL_HOST_PASSWORD = 'ivhxalyoajcrpecv'  # Replace with the 16-character app password from Gmail   
DEFAULT_FROM_EMAIL = 'ferosek13@gmail.com'
HR_EMAIL = 'ferosek13@gmail.com'  # Update with HR team email 

# You can set it to, for example, 10 MB:
DATA_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10 MB 
