# Generated by Django 5.1.5 on 2025-02-13 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoleMaster',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('comp_code', models.CharField(max_length=15)),
                ('role_name', models.CharField(max_length=50)),
                ('role_description', models.TextField()),
                ('created_by', models.BigIntegerField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.BigIntegerField(blank=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tbl_erp_smas_role_master',
            },
        ),
    ]
