# Generated by Django 5.1.5 on 2025-02-14 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolemaster',
            name='is_active',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
