# Generated by Django 5.1.6 on 2025-03-14 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0003_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRoleMapping',
            fields=[
                ('comp_code', models.CharField(max_length=15)),
                ('mappingid', models.BigAutoField(primary_key=True, serialize=False)),
                ('userid', models.BigIntegerField()),
                ('roleid', models.BigIntegerField()),
                ('role_start_date', models.DateField(blank=True, null=True)),
                ('role_to_date', models.DateField(blank=True, null=True)),
                ('instance_id', models.CharField(blank=True, max_length=50, null=True)),
                ('is_default_role', models.BooleanField(blank=True, null=True)),
                ('is_active', models.BooleanField()),
                ('created_by', models.BigIntegerField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.BigIntegerField(blank=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tbl_erp_smas_user_role_mapping',
            },
        ),
    ]
