# Generated by Django 5.1.6 on 2025-02-10 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeMaster',
            fields=[
                ('comp_code', models.CharField(max_length=15)),
                ('common_master_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('base_type', models.CharField(max_length=100)),
                ('base_value', models.CharField(max_length=100)),
                ('base_description', models.CharField(blank=True, max_length=500, null=True)),
                ('sequence_id', models.IntegerField()),
                ('instance_id', models.CharField(max_length=50)),
                ('is_active', models.CharField(max_length=2)),
                ('created_by', models.BigIntegerField(default=1)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.BigIntegerField(blank=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
