<<<<<<< HEAD
# Generated by Django 5.1.6 on 2025-02-08 16:28

import uuid
=======
# Generated by Django 5.1.6 on 2025-02-10 19:43

>>>>>>> 647d7efc32d3209de5e44fef4a43ff55abc592c3
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('comp_code', models.CharField(max_length=15)),
                ('prj_code', models.CharField(max_length=50)),
                ('prj_name', models.CharField(max_length=50)),
                ('project_description', models.TextField(max_length=500)),
                ('project_type', models.BigIntegerField()),
                ('project_value', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('timeline_from', models.CharField(blank=True, max_length=200, null=True)),
                ('timeline_to', models.CharField(blank=True, max_length=200, null=True)),
                ('prj_city', models.BigIntegerField()),
                ('consultant', models.CharField(blank=True, max_length=50, null=True)),
                ('main_contractor', models.CharField(blank=True, max_length=50, null=True)),
                ('sub_contractor', models.CharField(blank=True, max_length=50, null=True)),
                ('instance_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.BigIntegerField()),
            name='CodeMaster',
            fields=[
                ('comp_code', models.CharField(max_length=15)),
                ('common_master_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('base_type', models.CharField(max_length=100)),
                ('base_value', models.CharField(max_length=100)),
                ('base_description', models.CharField(blank=True, max_length=500, null=True)),
                ('sequence_id', models.IntegerField()),
                ('instance_id', models.CharField(max_length=50)),
                ('is_active', models.CharField(max_length=2)),
                ('created_by', models.BigIntegerField(default=1)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.BigIntegerField(blank=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
