# Generated by Django 5.1.5 on 2025-02-10 18:28

import django.utils.timezone
import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='PaycycleMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_code', models.CharField(max_length=20)),
                ('process_cycle_id', models.BigIntegerField()),
                ('process_cycle', models.BigIntegerField()),
                ('process_description', models.CharField(max_length=500)),
                ('pay_process_month', models.CharField(max_length=20)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('process_date', models.DateField(blank=True, null=True)),
                ('process_comp_flag', models.BigIntegerField()),
                ('hours_per_day', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('days_per_month', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('attendance_uom', models.BigIntegerField()),
                ('instance_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('max_mn_hrs', models.IntegerField(blank=True, null=True)),
                ('max_an_hrs', models.IntegerField(blank=True, null=True)),
                ('max_ot1_hrs', models.IntegerField(blank=True, null=True)),
                ('max_ot2_hrs', models.IntegerField(blank=True, null=True)),
                ('ot1_amt', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('ot2_amt', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('travel_time', models.FloatField(blank=True, null=True)),
                ('lunch_break', models.FloatField(blank=True, null=True)),
                ('ot_eligible', models.CharField(blank=True, max_length=1, null=True)),
                ('ot2_eligible', models.CharField(blank=True, max_length=1, null=True)),
                ('default_project', models.CharField(blank=True, max_length=30, null=True)),
                ('start_time', models.CharField(blank=True, max_length=30, null=True)),
                ('end_time', models.CharField(blank=True, max_length=30, null=True)),
                ('is_active', models.BooleanField()),
                ('created_by', models.BigIntegerField()),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_by', models.BigIntegerField(blank=True, null=True)),
                ('modified_on', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('comp_code', models.CharField(max_length=15)),
                ('prj_code', models.CharField(max_length=50)),
                ('prj_name', models.CharField(max_length=50)),
                ('project_description', models.TextField(max_length=500)),
                ('project_type', models.BigIntegerField()),
                ('project_value', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('timeline_from', models.CharField(blank=True, max_length=200, null=True)),
                ('timeline_to', models.CharField(blank=True, max_length=200, null=True)),
                ('prj_city', models.BigIntegerField()),
                ('consultant', models.CharField(blank=True, max_length=50, null=True)),
                ('main_contractor', models.CharField(blank=True, max_length=50, null=True)),
                ('sub_contractor', models.CharField(blank=True, max_length=50, null=True)),
                ('instance_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CodeMaster',
            fields=[
                ('comp_code', models.CharField(max_length=15)),
                ('common_master_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('base_type', models.CharField(max_length=100)),
                ('base_value', models.CharField(max_length=100)),
                ('base_description', models.CharField(blank=True, max_length=500, null=True)),
                ('sequence_id', models.IntegerField()),
                ('instance_id', models.CharField(max_length=50)),
                ('is_active', models.CharField(max_length=2)),
                ('created_by', models.BigIntegerField(default=1)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.BigIntegerField(blank=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
