# Generated by Django 5.1.6 on 2025-02-11 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project',
            new_name='projectMatster',
        ),
    ]
