# Generated by Django 5.1.5 on 2025-02-09 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermaster',
            name='created_by',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usermaster',
            name='gender',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='usermaster',
            name='is_active',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='usermaster',
            name='modified_by',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usermaster',
            name='profile_picture',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
