# Generated by Django 5.1.6 on 2025-02-15 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codemaster',
            name='modified_by',
            field=models.BigIntegerField(default=1, null=True),
        ),
    ]
