# Generated by Django 5.1.5 on 2025-02-10 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paycyclemaster',
            name='is_active',
            field=models.CharField(max_length=1),
        ),
    ]
