# Generated by Django 5.1.5 on 2025-02-16 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_alter_paycyclemaster_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paycyclemaster',
            name='process_cycle',
            field=models.CharField(),
        ),
    ]
