# Generated by Django 5.1.6 on 2025-02-19 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_alter_projectmatster_timeline_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmatster',
            name='project_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
