# Generated by Django 5.1.5 on 2025-02-16 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_alter_usermaster_created_by_alter_usermaster_gender_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usermaster',
            table='tbl_erp_smas_user_master',
        ),
    ]
