# Generated by Django 5.1.5 on 2025-02-21 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_alter_projectmatster_project_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeedModel',
            fields=[
                ('seed_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('comp_code', models.CharField(default='1000', max_length=15)),
                ('seed_code', models.CharField(max_length=50)),
                ('seed_group', models.CharField(max_length=50)),
                ('seed_type', models.CharField(max_length=50)),
                ('seed_prefix', models.CharField(max_length=50)),
                ('seed_length', models.BigIntegerField()),
                ('seed_start_num', models.BigIntegerField()),
                ('seed_next_num', models.BigIntegerField()),
                ('seed_timeline_from', models.DateField()),
                ('seed_timeline_to', models.DateField()),
                ('seed_inc_by', models.BigIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.BigIntegerField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.BigIntegerField()),
                ('modified_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'payroll_seedmaster',
            },
        ),
    ]
