# Generated by Django 5.1.5 on 2025-02-16 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_alter_codemaster_modified_by'),
        ('payroll', '0002_rename_project_projectmatster'),
        ('payroll', '0003_alter_paycyclemaster_process_cycle'),
    ]

    operations = [
    ]
