# Generated by Django 5.1.5 on 2025-03-01 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_seedmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeMaster',
            fields=[
                ('comp_code', models.CharField(max_length=10)),
                ('grade_id', models.AutoField(primary_key=True, serialize=False)),
                ('grade_code', models.CharField(max_length=20, unique=True)),
                ('grade_desc', models.TextField(default='N/A')),
                ('nationality', models.CharField(max_length=50)),
                ('attendance_days', models.IntegerField(default=0)),
                ('leave_days', models.IntegerField(default=0)),
                ('passage_amount_adult', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('passage_amount_child', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('allowance1', models.CharField(max_length=20)),
                ('allowance2', models.CharField(max_length=20)),
                ('allowance3', models.CharField(max_length=20)),
                ('allowance4', models.CharField(max_length=20)),
                ('allowance5', models.CharField(max_length=20)),
                ('allowance6', models.CharField(max_length=20)),
                ('allowance7', models.CharField(max_length=20)),
                ('allowance8', models.CharField(max_length=20)),
                ('is_active', models.CharField(max_length=1)),
                ('instance_id', models.CharField(max_length=50)),
                ('created_by', models.IntegerField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
