# Generated by Django 5.1.6 on 2025-03-04 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0005_grademaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('menu_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('comp_code', models.CharField(default='1001', max_length=10)),
                ('menu_name', models.CharField(max_length=50)),
                ('quick_path', models.BigIntegerField()),
                ('screen_name', models.CharField(blank=True, max_length=50, null=True)),
                ('url', models.CharField(blank=True, max_length=100, null=True)),
                ('module_id', models.CharField(blank=True, max_length=50, null=True)),
                ('parent_menu_id', models.CharField(blank=True, max_length=50, null=True)),
                ('display_order', models.BigIntegerField()),
                ('instance_id', models.CharField(max_length=50)),
                ('buffer1', models.CharField(blank=True, max_length=10, null=True)),
                ('buffer2', models.CharField(blank=True, max_length=10, null=True)),
                ('buffer3', models.CharField(blank=True, max_length=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.BigIntegerField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.BigIntegerField(blank=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('is_add', models.BooleanField(blank=True, null=True)),
                ('is_view', models.BooleanField(blank=True, null=True)),
                ('is_edit', models.BooleanField(blank=True, null=True)),
                ('is_delete', models.BooleanField(blank=True, null=True)),
                ('is_execute', models.IntegerField(blank=True, null=True)),
                ('app_id', models.IntegerField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
