# Generated by Django 5.1.6 on 2025-03-02 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0005_grademaster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmatster',
            name='prj_city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
