# Generated by Django 5.1.6 on 2025-03-04 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0006_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleMenuMapping',
            fields=[
                ('comp_code', models.CharField(default='1000', max_length=15)),
                ('roll_id', models.PositiveBigIntegerField()),
                ('menu_id', models.PositiveBigIntegerField()),
                ('mapping_id', models.AutoField(primary_key=True, serialize=False)),
                ('add', models.BooleanField(blank=True, null=True)),
                ('view', models.BooleanField(blank=True, null=True)),
                ('delete', models.BooleanField(blank=True, null=True)),
                ('modify', models.BooleanField(blank=True, null=True)),
                ('instance_id', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.BigIntegerField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.BigIntegerField(blank=True, null=True)),
                ('modified_on', models.DateTimeField(blank=True, null=True)),
                ('execute', models.BooleanField(blank=True, null=True)),
            ],
        ),
    ]
