# Generated by Django 5.1.6 on 2025-03-04 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0007_rolemenumapping'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rolemenumapping',
            old_name='roll_id',
            new_name='role_id',
        ),
    ]
