# Generated by Django 5.1.6 on 2025-03-04 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0008_rename_roll_id_rolemenumapping_role_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rolemenumapping',
            name='comp_code',
        ),
    ]
