# Generated by Django 5.1.6 on 2025-03-04 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0009_remove_rolemenumapping_comp_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolemenumapping',
            name='comp_code',
            field=models.CharField(default='1000', max_length=15),
        ),
    ]
