# Generated by Django 5.1.6 on 2025-03-04 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0010_rolemenumapping_comp_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RoleMenuMapping',
        ),
    ]
