# Generated by Django 5.1.6 on 2025-03-04 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0006_alter_projectmatster_prj_city'),
        ('payroll', '0013_rename_rolemenumapping_role_menumapping'),
    ]

    operations = [
    ]
