# Generated by Django 5.1.6 on 2025-03-04 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0014_merge_20250305_0104'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Role_MenuMapping',
            new_name='RoleMenuMapping',
        ),
    ]
