# Generated by Django 5.1.6 on 2025-03-04 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0015_rename_role_menumapping_rolemenumapping'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RoleMenuMapping',
            new_name='RoleMenu',
        ),
    ]
