# Generated by Django 5.1.6 on 2025-03-06 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0016_rename_rolemenumapping_rolemenu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_code', models.CharField(max_length=50)),
                ('unique_id', models.BigIntegerField(unique=True)),
                ('holiday', models.CharField(blank=True, max_length=50, null=True)),
                ('holiday_type', models.BigIntegerField()),
                ('holiday_date', models.DateField()),
                ('holiday_day', models.CharField(max_length=50)),
                ('holiday_description', models.CharField(max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.BigIntegerField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.BigIntegerField(blank=True, null=True)),
                ('modified_on', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
