# Generated by Django 5.1.6 on 2025-03-06 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0017_holiday'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Holiday',
            new_name='HolidayMaster',
        ),
    ]
