# Generated by Django 5.1.6 on 2025-03-05 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0017_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolemenu',
            name='created_by',
            field=models.BigIntegerField(default=1),
        ),
    ]
