# Generated by Django 5.1.6 on 2025-03-05 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0018_alter_rolemenu_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='created_by',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='employee',
            name='modified_by',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rolemenu',
            name='created_by',
            field=models.BigIntegerField(),
        ),
    ]
