# Generated by Django 5.1.6 on 2025-03-06 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0018_rename_holiday_holidaymaster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holidaymaster',
            name='id',
        ),
        migrations.AlterField(
            model_name='holidaymaster',
            name='unique_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
