# Generated by Django 5.1.6 on 2025-03-05 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0019_employee_created_by_employee_modified_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='created_on',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_acc_no',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='instance_id',
            field=models.CharField(default='NEWID()', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='pay_process_flag',
            field=models.IntegerField(null=True),
        ),
    ]
