# Generated by Django 5.1.6 on 2025-03-06 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0020_alter_employee_created_on_alter_employee_emp_acc_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='parent_menu_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
