# Generated by Django 5.1.6 on 2025-03-06 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0021_alter_menu_parent_menu_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermaster',
            name='user_master_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
