# Generated by Django 5.1.6 on 2025-03-06 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0022_alter_usermaster_user_master_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermaster',
            name='user_master_id',
            field=models.CharField(primary_key=True, serialize=False),
        ),
    ]
