# Generated by Django 5.1.6 on 2025-03-06 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0025_remove_employee_id_alter_employee_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='passport_validity',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
