# Generated by Django 5.1.6 on 2025-03-06 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0026_alter_employee_passport_validity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_type',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
