# Generated by Django 5.1.6 on 2025-03-06 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0028_alter_employee_desig_code_alter_employee_email2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='country_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_acc_no',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='prj_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
