# Generated by Django 5.1.5 on 2025-03-07 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0019_remove_holidaymaster_id_and_more'),
        ('payroll', '0029_alter_employee_country_code_and_more'),
    ]

    operations = [
    ]
