# Generated by Django 5.1.6 on 2025-03-09 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0030_merge_20250309_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holidaymaster',
            name='holiday_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
