# Generated by Django 5.1.5 on 2025-03-07 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0030_merge_20250307_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='parent_menu_id',
            field=models.CharField(blank=True, null=True),
        ),
    ]
