# Generated by Django 5.1.5 on 2025-03-07 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0031_alter_menu_parent_menu_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paycyclemaster',
            name='attendance_uom',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='paycyclemaster',
            name='process_comp_flag',
            field=models.CharField(max_length=20),
        ),
    ]
