# Generated by Django 5.1.6 on 2025-03-10 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0031_alter_holidaymaster_holiday_type'),
        ('payroll', '0032_alter_paycyclemaster_attendance_uom_and_more'),
    ]

    operations = [
    ]
