# Generated by Django 5.1.6 on 2025-03-10 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0033_merge_20250310_1320'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
