# Generated by Django 5.1.6 on 2025-03-10 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0034_delete_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('emp_code', models.CharField(blank=True, max_length=50, null=True)),
                ('emp_name', models.CharField(max_length=100)),
                ('surname', models.CharField(blank=True, max_length=50, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('emp_sex', models.CharField(choices=[('1', 'Male'), ('2', 'Female')], default='1', max_length=1)),
                ('emp_status', models.CharField(blank=True, max_length=50, null=True)),
                ('father_name', models.CharField(blank=True, max_length=50, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=50, null=True)),
                ('nationality', models.CharField(blank=True, max_length=50, null=True)),
                ('religion', models.CharField(blank=True, max_length=50, null=True)),
                ('qualification', models.CharField(blank=True, max_length=50, null=True)),
                ('emp_marital_status', models.CharField(choices=[('1', 'Single'), ('2', 'Married')], default='1', max_length=1)),
                ('spouse_name', models.CharField(blank=True, max_length=50, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('family_status', models.CharField(blank=True, max_length=50, null=True)),
                ('res_country_code', models.CharField(blank=True, max_length=10, null=True)),
                ('res_phone_no', models.CharField(blank=True, max_length=20, null=True)),
                ('res_addr_line1', models.CharField(blank=True, max_length=100, null=True)),
                ('res_addr_line2', models.CharField(blank=True, max_length=100, null=True)),
                ('res_city', models.CharField(blank=True, max_length=50, null=True)),
                ('res_state', models.CharField(blank=True, max_length=50, null=True)),
                ('local_country_code', models.CharField(blank=True, max_length=10, null=True)),
                ('local_phone_no', models.CharField(blank=True, max_length=20, null=True)),
                ('local_addr_line1', models.CharField(blank=True, max_length=100, null=True)),
                ('local_addr_line2', models.CharField(blank=True, max_length=100, null=True)),
                ('labour_id', models.CharField(blank=True, max_length=50, null=True)),
                ('process_cycle', models.CharField(blank=True, max_length=50, null=True)),
                ('basic_pay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('allowance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('grade_code', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=1, null=True)),
                ('designation', models.CharField(blank=True, max_length=50, null=True)),
                ('department', models.CharField(blank=True, max_length=50, null=True)),
                ('date_of_join', models.DateField(blank=True, null=True)),
                ('date_of_rejoin', models.DateField(blank=True, null=True)),
                ('depend_count', models.IntegerField(blank=True, null=True)),
                ('child_count', models.IntegerField(blank=True, null=True)),
                ('employee_bank', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_branch', models.CharField(blank=True, max_length=100, null=True)),
                ('account_no', models.CharField(blank=True, max_length=20, null=True)),
                ('bank_loan', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_by', models.BigIntegerField(default=1)),
                ('modified_by', models.BigIntegerField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
