# Generated by Django 5.1.6 on 2025-03-11 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0036_alter_employee_created_on_alter_employee_modified_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='issued_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='passport_details',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='passport_document',
            field=models.FileField(blank=True, null=True, upload_to='passport_documents/'),
        ),
    ]
