# Generated by Django 5.1.6 on 2025-03-11 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0037_employee_expiry_date_employee_issued_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emirate_document',
            field=models.FileField(blank=True, null=True, upload_to='employee_documents/emirate_documents/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='emirate_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='emirate_issued',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='mohra_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='uid_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='visa_document',
            field=models.FileField(blank=True, null=True, upload_to='employee_documents/visa_documents/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='visa_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='visa_issued',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='visa_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='work_permit_document',
            field=models.FileField(blank=True, null=True, upload_to='employee_documents/work_permit_documents/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='work_permit_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='work_permit_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='passport_document',
            field=models.FileField(blank=True, null=True, upload_to='employee_documents/passport_documents/'),
        ),
    ]
