# Generated by Django 5.1.6 on 2025-03-11 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0038_employee_emirate_document_employee_emirate_expiry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emirate_document',
            field=models.FileField(blank=True, null=True, upload_to='employee_documents/{emp_code}/'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='passport_document',
            field=models.FileField(blank=True, null=True, upload_to='employee_documents/{emp_code}/'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='visa_document',
            field=models.FileField(blank=True, null=True, upload_to='employee_documents/{emp_code}/'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='work_permit_document',
            field=models.FileField(blank=True, null=True, upload_to='employee_documents/{emp_code}/'),
        ),
    ]
