# Generated by Django 5.1.6 on 2025-03-11 11:04

import payroll.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0039_alter_employee_emirate_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emirate_document',
            field=models.FileField(blank=True, null=True, upload_to=payroll.models.employee_document_path),
        ),
        migrations.AlterField(
            model_name='employee',
            name='passport_document',
            field=models.FileField(blank=True, null=True, upload_to=payroll.models.employee_document_path),
        ),
        migrations.AlterField(
            model_name='employee',
            name='visa_document',
            field=models.FileField(blank=True, null=True, upload_to=payroll.models.employee_document_path),
        ),
        migrations.AlterField(
            model_name='employee',
            name='work_permit_document',
            field=models.FileField(blank=True, null=True, upload_to=payroll.models.employee_document_path),
        ),
    ]
