# Generated by Django 5.1.6 on 2025-03-11 19:19

import payroll.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0040_alter_employee_emirate_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='profile_picture',
            field=models.FileField(blank=True, null=True, upload_to=payroll.models.employee_document_path),
        ),
    ]
