# Generated by Django 5.1.6 on 2025-03-11 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0041_employee_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_marital_status',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
