# Generated by Django 5.1.6 on 2025-03-11 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0042_alter_employee_emp_marital_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermaster',
            name='gender',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
