# Generated by Django 5.1.6 on 2025-03-11 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0043_alter_usermaster_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='comp_code',
            field=models.CharField(default=1000, max_length=15),
        ),
    ]
