# Generated by Django 5.1.6 on 2025-03-12 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0044_employee_comp_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='grade_code',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
