# Generated by Django 5.1.6 on 2025-03-13 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0045_alter_employee_grade_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyMaster',
            fields=[
                ('company_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('company_code', models.CharField(max_length=15)),
                ('company_name', models.CharField(max_length=100)),
                ('company_status', models.CharField(max_length=5)),
                ('inception_date', models.CharField(max_length=200)),
                ('labour_ministry_id', models.CharField(blank=True, max_length=50, null=True)),
                ('labour_bank_acc_no', models.CharField(blank=True, max_length=50, null=True)),
                ('currency_code', models.CharField(max_length=5)),
                ('address_line1', models.CharField(blank=True, max_length=50, null=True)),
                ('address_line2', models.CharField(blank=True, max_length=50, null=True)),
                ('address_line_city', models.CharField(blank=True, max_length=50, null=True)),
                ('address_line_state', models.CharField(blank=True, max_length=50, null=True)),
                ('country_code', models.CharField(max_length=5)),
                ('telephone1', models.CharField(blank=True, max_length=20, null=True)),
                ('telephone2', models.CharField(blank=True, max_length=20, null=True)),
                ('fax_number', models.CharField(blank=True, max_length=20, null=True)),
                ('mail_id', models.CharField(blank=True, max_length=40, null=True)),
                ('social_media_id', models.CharField(blank=True, max_length=50, null=True)),
                ('instance_id', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.BigIntegerField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.BigIntegerField(blank=True, null=True)),
                ('modified_on', models.DateTimeField(blank=True, null=True)),
                ('image_url', models.CharField(blank=True, max_length=100, null=True)),
                ('salary_roundoff', models.CharField(blank=True, max_length=50, null=True)),
                ('logo_blob', models.BinaryField(blank=True, null=True)),
                ('po_box', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
