# Generated by Django 5.1.6 on 2025-03-13 16:32

import payroll.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0046_companymaster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companymaster',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to=payroll.models.company_logo_upload_path),
        ),
    ]
