# Generated by Django 5.1.6 on 2025-03-14 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0047_alter_companymaster_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grademaster',
            name='allowance1',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='grademaster',
            name='allowance2',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='grademaster',
            name='allowance3',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='grademaster',
            name='allowance4',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='grademaster',
            name='allowance5',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='grademaster',
            name='allowance6',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='grademaster',
            name='allowance7',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='grademaster',
            name='allowance8',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='rolemenu',
            name='created_by',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
