# Generated by Django 5.1.6 on 2025-03-15 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0048_alter_grademaster_allowance1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companymaster',
            name='country_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
