# Generated by Django 5.1.6 on 2025-03-15 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0049_alter_companymaster_country_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerAttendanceRegister',
            fields=[
                ('comp_code', models.CharField(max_length=50)),
                ('unique_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('employee_code', models.CharField(max_length=50)),
                ('pay_cycle', models.BigIntegerField()),
                ('pay_process_month', models.CharField(max_length=50)),
                ('project_code', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateField()),
                ('attendance_type', models.BigIntegerField()),
                ('morning', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('afternoon', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('ot1', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('ot2', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.BigIntegerField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.BigIntegerField(blank=True, null=True)),
                ('modified_on', models.DateTimeField(blank=True, null=True)),
                ('in_time', models.CharField(blank=True, max_length=20, null=True)),
                ('out_time', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
