# Generated by Django 5.1.6 on 2025-03-15 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0050_workerattendanceregister'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerattendanceregister',
            name='pay_cycle',
            field=models.CharField(max_length=100),
        ),
    ]
