# Generated by Django 5.1.6 on 2025-03-16 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0051_alter_workerattendanceregister_pay_cycle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='comp_code',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='rolemenu',
            name='comp_code',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='seedmodel',
            name='comp_code',
            field=models.CharField(max_length=15),
        ),
    ]
