# Generated by Django 5.1.5 on 2025-02-09 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserMaster',
            fields=[
                ('comp_code', models.CharField(max_length=15)),
                ('user_master_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('user_id', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('dob', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('gender', models.BigIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('instance_id', models.CharField(max_length=50)),
                ('profile_picture', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by', models.BigIntegerField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.BigIntegerField(blank=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('emp_code', models.CharField(blank=True, max_length=20, null=True)),
                ('user_paycycles', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
